2021-08-08 17:17:33,539 [http-nio-8081-exec-9] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 17:17:33,550 [http-nio-8081-exec-9] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 17:17:33,555 [http-nio-8081-exec-9] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 17:17:52,536 [http-nio-8081-exec-4] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 17:17:52,537 [http-nio-8081-exec-4] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 17:17:52,538 [http-nio-8081-exec-4] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 17:59:47,005 [http-nio-8081-exec-6] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 17:59:47,006 [http-nio-8081-exec-6] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 17:59:47,007 [http-nio-8081-exec-6] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 17:59:47,064 [http-nio-8081-exec-6] INFO  org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:14:18,387 [http-nio-8081-exec-8] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:14:18,387 [http-nio-8081-exec-8] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:14:18,388 [http-nio-8081-exec-8] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:14:18,434 [http-nio-8081-exec-8] INFO  org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:14:37,098 [http-nio-8081-exec-2] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:14:37,110 [http-nio-8081-exec-2] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:14:37,114 [http-nio-8081-exec-2] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:14:37,249 [http-nio-8081-exec-2] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:23:19,049 [http-nio-8081-exec-11] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:23:19,050 [http-nio-8081-exec-11] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:23:19,051 [http-nio-8081-exec-11] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:23:19,102 [http-nio-8081-exec-11] INFO  org.anatkor.dao.UserDao- User nuser is added
2021-08-08 18:23:19,105 [http-nio-8081-exec-11] INFO  org.anatkor.dao.UserDao- User nuser with role  is added
2021-08-08 18:23:19,109 [http-nio-8081-exec-12] DEBUG org.anatkor.servlets.UsersServlet- User servlet called
2021-08-08 18:23:19,110 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:23:19,110 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:23:33,093 [http-nio-8081-exec-18] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:23:33,094 [http-nio-8081-exec-18] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:23:33,094 [http-nio-8081-exec-18] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:23:33,140 [http-nio-8081-exec-18] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:28:38,925 [http-nio-8081-exec-11] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 18:28:38,926 [http-nio-8081-exec-11] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:28:38,927 [http-nio-8081-exec-11] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:28:50,394 [http-nio-8081-exec-13] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 18:28:50,394 [http-nio-8081-exec-13] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:28:50,395 [http-nio-8081-exec-13] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:29:00,617 [http-nio-8081-exec-16] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 18:29:00,617 [http-nio-8081-exec-16] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:29:00,617 [http-nio-8081-exec-16] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:29:17,577 [http-nio-8081-exec-12] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:29:17,578 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:29:17,579 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:29:17,624 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:29:48,520 [http-nio-8081-exec-15] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:29:48,520 [http-nio-8081-exec-15] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:29:48,521 [http-nio-8081-exec-15] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:29:48,568 [http-nio-8081-exec-15] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:29:59,071 [http-nio-8081-exec-17] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:29:59,072 [http-nio-8081-exec-17] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:29:59,072 [http-nio-8081-exec-17] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:29:59,115 [http-nio-8081-exec-17] INFO  org.anatkor.dao.UserDao- User lehak is added
2021-08-08 18:29:59,116 [http-nio-8081-exec-17] INFO  org.anatkor.dao.UserDao- User lehak with role  is added
2021-08-08 18:31:17,545 [http-nio-8081-exec-20] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:31:17,545 [http-nio-8081-exec-20] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:31:17,547 [http-nio-8081-exec-20] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:31:17,589 [http-nio-8081-exec-20] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:31:24,723 [http-nio-8081-exec-12] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:31:24,723 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:31:24,724 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:31:24,884 [http-nio-8081-exec-12] INFO  org.anatkor.dao.UserDao- User nuserer is added
2021-08-08 18:31:24,886 [http-nio-8081-exec-12] INFO  org.anatkor.dao.UserDao- User nuserer with role  is added
2021-08-08 18:32:29,306 [http-nio-8081-exec-15] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 18:32:29,307 [http-nio-8081-exec-15] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:32:29,307 [http-nio-8081-exec-15] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:32:42,035 [http-nio-8081-exec-17] DEBUG org.anatkor.servlets.UserServlet- User servlet called
2021-08-08 18:32:42,035 [http-nio-8081-exec-17] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:32:42,036 [http-nio-8081-exec-17] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:32:59,650 [http-nio-8081-exec-12] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:32:59,651 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:32:59,652 [http-nio-8081-exec-12] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:32:59,695 [http-nio-8081-exec-12] INFO  org.anatkor.dao.UserDao- User df is added
2021-08-08 18:32:59,696 [http-nio-8081-exec-12] INFO  org.anatkor.dao.UserDao- User df with role  is added
2021-08-08 18:41:41,541 [http-nio-8081-exec-14] DEBUG org.anatkor.servlets.AddUserServlet- AddUser servlet called
2021-08-08 18:41:41,541 [http-nio-8081-exec-14] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:41:41,542 [http-nio-8081-exec-14] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:41:41,584 [http-nio-8081-exec-14] INFO  org.anatkor.dao.UserDao- User пар is added
2021-08-08 18:41:41,586 [http-nio-8081-exec-14] INFO  org.anatkor.dao.UserDao- User пар with role  is added
2021-08-08 18:43:54,074 [http-nio-8081-exec-20] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:43:54,084 [http-nio-8081-exec-20] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:43:54,088 [http-nio-8081-exec-20] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:44:03,801 [http-nio-8081-exec-18] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:44:03,802 [http-nio-8081-exec-18] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:44:03,802 [http-nio-8081-exec-18] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:44:14,229 [http-nio-8081-exec-19] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:44:14,229 [http-nio-8081-exec-19] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:44:14,230 [http-nio-8081-exec-19] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:44:20,902 [http-nio-8081-exec-16] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:44:20,902 [http-nio-8081-exec-16] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:44:20,903 [http-nio-8081-exec-16] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:34,694 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:34,694 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:34,695 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:41,715 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:41,715 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:41,716 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:43,722 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:43,722 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:43,722 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:44,363 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:44,364 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:44,364 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:44,882 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:44,883 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:44,883 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:45,347 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:45,347 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:45,347 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:45,858 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:45,858 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:45,859 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:46,375 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:46,375 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:46,375 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:46,978 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:46,979 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:46,979 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:47,435 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:47,435 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:47,436 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:47,863 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:47,864 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:47,864 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:48,315 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:48,315 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:48,315 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:48,826 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:48,827 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:48,827 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:49,783 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:49,783 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:49,784 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:50,291 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:50,291 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:50,291 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:54,483 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:54,483 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:54,484 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:55,104 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:55,104 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:55,104 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:55,580 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:55,580 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:55,580 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:56,096 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:56,096 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:56,096 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:56,561 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:56,561 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:56,561 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:57,611 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:57,612 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:57,612 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:45:58,083 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:45:58,084 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:45:58,084 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:00,029 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:00,029 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:00,029 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:00,620 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:00,620 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:00,621 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:01,492 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:01,492 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:01,493 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:02,097 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:02,097 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:02,097 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:03,308 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:03,308 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:03,308 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:04,084 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:04,085 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:04,085 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:06,957 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:06,957 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:06,958 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:08,086 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:08,086 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:08,086 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:26,799 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:26,800 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:26,800 [http-nio-8081-exec-27] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:35,369 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:35,369 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:35,369 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:46:36,268 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:46:36,268 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:46:36,268 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:47:41,639 [http-nio-8081-exec-26] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:48:39,515 [http-nio-8081-exec-23] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:48:46,359 [http-nio-8081-exec-24] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:48:46,359 [http-nio-8081-exec-24] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:48:46,360 [http-nio-8081-exec-24] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:48:54,291 [http-nio-8081-exec-25] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:01,468 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:02,047 [http-nio-8081-exec-22] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:02,787 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:03,192 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:03,603 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:10,785 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:31,463 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:31,463 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:49:31,464 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:49:37,155 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:41,712 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:49:41,712 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:49:41,713 [http-nio-8081-exec-30] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:51:02,070 [http-nio-8081-exec-22] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:51:02,071 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:51:02,071 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:51:46,148 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:51:46,148 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:51:46,149 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:51:49,931 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:51:57,514 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:51:57,515 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:51:57,515 [http-nio-8081-exec-21] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:52:04,515 [http-nio-8081-exec-22] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 18:52:04,516 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:52:04,516 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:52:21,035 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:52:21,035 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:52:21,092 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:56:37,212 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:56:37,213 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:56:37,261 [http-nio-8081-exec-22] DEBUG org.anatkor.dao.UserDao- SQLException during Add admin processing class org.anatkor.dao.Utils. ERROR: duplicate key value violates unique constraint "usr_username_key"
  Detail: Key (username)=(admin) already exists.
2021-08-08 18:57:36,339 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:57:36,340 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:57:36,381 [http-nio-8081-exec-28] INFO  org.anatkor.dao.UserDao- User adminвапі           is added
2021-08-08 18:57:36,384 [http-nio-8081-exec-28] INFO  org.anatkor.dao.UserDao- User adminвапі           with role  is added
2021-08-08 18:57:58,661 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 18:57:58,661 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 18:57:58,703 [http-nio-8081-exec-26] INFO  org.anatkor.dao.UserDao- User вапіва                  is added
2021-08-08 18:57:58,705 [http-nio-8081-exec-26] INFO  org.anatkor.dao.UserDao- User вапіва                  with role  is added
2021-08-08 19:01:09,347 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 19:01:09,348 [http-nio-8081-exec-29] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 19:01:09,392 [http-nio-8081-exec-29] INFO  org.anatkor.dao.UserDao- User в is added
2021-08-08 19:01:09,394 [http-nio-8081-exec-29] INFO  org.anatkor.dao.UserDao- User в with role  is added
2021-08-08 19:01:09,397 [http-nio-8081-exec-25] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:01:53,451 [http-nio-8081-exec-23] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 19:01:53,452 [http-nio-8081-exec-23] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 19:01:53,608 [http-nio-8081-exec-23] INFO  org.anatkor.dao.UserDao- User вапів is added
2021-08-08 19:01:53,610 [http-nio-8081-exec-23] INFO  org.anatkor.dao.UserDao- User вапів with role  is added
2021-08-08 19:01:53,613 [http-nio-8081-exec-24] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:02:30,153 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 19:02:30,153 [http-nio-8081-exec-26] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 19:02:30,191 [http-nio-8081-exec-26] INFO  org.anatkor.dao.UserDao- User віапівап is added
2021-08-08 19:02:30,192 [http-nio-8081-exec-26] INFO  org.anatkor.dao.UserDao- User віапівап with role  is added
2021-08-08 19:02:38,177 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:02:54,963 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 19:02:54,964 [http-nio-8081-exec-28] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 19:02:55,007 [http-nio-8081-exec-28] INFO  org.anatkor.dao.UserDao- User admin444 is added
2021-08-08 19:02:55,008 [http-nio-8081-exec-28] INFO  org.anatkor.dao.UserDao- User admin444 with role  is added
2021-08-08 19:03:08,072 [http-nio-8081-exec-25] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:43,219 [http-nio-8081-exec-26] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:44,998 [http-nio-8081-exec-22] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:45,559 [http-nio-8081-exec-24] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:45,995 [http-nio-8081-exec-28] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:46,454 [http-nio-8081-exec-30] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:47,313 [http-nio-8081-exec-26] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:03:47,822 [http-nio-8081-exec-22] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:04:00,552 [http-nio-8081-exec-24] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:04:00,552 [http-nio-8081-exec-24] DEBUG org.anatkor.dao.Utils- connection try
2021-08-08 19:04:00,553 [http-nio-8081-exec-24] DEBUG org.anatkor.dao.Utils- connection created succesfully
2021-08-08 19:04:06,408 [http-nio-8081-exec-25] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:04:07,425 [http-nio-8081-exec-21] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:04:07,792 [http-nio-8081-exec-27] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:04:08,132 [http-nio-8081-exec-23] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
2021-08-08 19:04:08,472 [http-nio-8081-exec-29] DEBUG org.anatkor.servlets.LoginServlet- User servlet called
